# SPDX-License-Identifier: Apache-2.0
[package]
name = "substrait-gen"
version = "0.61.0"
edition = "2024"
rust-version = "1.88.0"
description = "Code generation for substrait-rs"
publish = false

[dependencies]
heck = "0.5.0"
pbjson-build = "0.8.0"
prettyplease = "0.2.37"
prost-build = { version = "0.14.1", default-features = false }
schemars = "0.8.22"
semver = "1.0.27"
serde_yaml = "0.9.34"
syn = "2.0.104"
typify = "0.5.0"
walkdir = "2.5.0"
